services:
  fund:
    image: docker.1ms.run/openjdk:21-jdk
    container_name: trader-collector
    restart: unless-stopped
    volumes:
      - /opt/trader/config.properties:/app/config.properties
      - ./trader-collector.jar:/app/trader-collector.jar
      - ./config:/app/config
      - ./logs:/app/logs
      - ./bin:/app/bin
    working_dir: /app
    command: sh /app/bin/run.sh
    environment:
      - CONFIG_PATH=/app/config.properties
      - TZ=Asia/Shanghai
      - JAVA_OPTS=-Xms512m -Xmx1024m
    ports:
      - "18080:18080"
