server:
  port: 8080

spring:
  application:
    name: trader-admin
  profiles:
    active: dev

mybatis-plus:
  type-aliases-package: cc.riskswap.trader.admin.dao.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto

trader:
  node:
    type: ADMIN
  redis:
    enabled: true
    host: localhost
    port: 6379
    password: hy123!!!
    database: 0
  mysql:
    enabled: true
    url: jdbc:mysql://localhost:3306/trader?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  clickhouse:
    enabled: true
    url: jdbc:clickhouse://localhost:8123/trader
    username: default
    password: default
    driver-class-name: com.clickhouse.jdbc.ClickHouseDriver
  db:
    init:
      enabled: true
      mysql-script: classpath:db/mysql.sql
      clickhouse-script: classpath:db/clickhouse.sql
    upgrade:
      mysql-location: classpath*:db/upgrade/mysql/*.sql
      clickhouse-location: classpath*:db/upgrade/clickhouse/*.sql
  monitor:
    enabled: false
  log:
    home: logs
  wecom:
    webhook-url: ${WECOM_WEBHOOK_URL:https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=e4805ac5-e50e-4711-baf7-abe3eebf3a13}
  matrix:
    homeserver: ${MATRIX_HOMESERVER:}
    room-id: ${MATRIX_ROOM_ID:}
    access-token: ${MATRIX_ACCESS_TOKEN:}
# logging:
#   level:
#     cc.riskswap.trader.admin.dao.mapper: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
