ALTER TABLE users
    MODIFY COLUMN id INT NOT NULL AUTO_INCREMENT COMMENT '主键ID';

ALTER TABLE fund
    MODIFY COLUMN id INT NOT NULL AUTO_INCREMENT COMMENT '主键ID';

ALTER TABLE import_log
    MODIFY COLUMN id INT NOT NULL AUTO_INCREMENT COMMENT '主键ID';

ALTER TABLE msg_push_log
    MODIFY COLUMN id INT NOT NULL AUTO_INCREMENT COMMENT '主键ID';

ALTER TABLE investment
    MODIFY COLUMN id INT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    MODIFY COLUMN broker_id INT DEFAULT NULL COMMENT '券商ID';

ALTER TABLE investment_log
    MODIFY COLUMN id INT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    MODIFY COLUMN investment_id INT NOT NULL COMMENT '投资ID';

ALTER TABLE investment_trading
    MODIFY COLUMN id INT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    MODIFY COLUMN investment_log_id INT DEFAULT NULL COMMENT '投资日志ID',
    MODIFY COLUMN investment_id INT NOT NULL COMMENT '投资ID';

ALTER TABLE investment_position
    MODIFY COLUMN id INT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    MODIFY COLUMN investment_id INT NOT NULL COMMENT '投资ID',
    MODIFY COLUMN investment_log_id INT DEFAULT NULL COMMENT '投资日志ID';

ALTER TABLE broker
    MODIFY COLUMN id INT NOT NULL AUTO_INCREMENT COMMENT '主键ID';

ALTER TABLE system_sql_script
    MODIFY COLUMN id INT NOT NULL AUTO_INCREMENT COMMENT '主键ID';

ALTER TABLE task_log
    MODIFY COLUMN id INT NOT NULL AUTO_INCREMENT;

ALTER TABLE node_group
    MODIFY COLUMN id INT NOT NULL AUTO_INCREMENT COMMENT '主键ID';

ALTER TABLE node
    MODIFY COLUMN id INT NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    MODIFY COLUMN node_group_id INT NOT NULL COMMENT '节点分组ID';

ALTER TABLE system_task
    MODIFY COLUMN id INT NOT NULL AUTO_INCREMENT;

ALTER TABLE system_task_run_log
    MODIFY COLUMN id INT NOT NULL AUTO_INCREMENT;

